[package]
name = "mrm_app"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.awkernel_async_lib]
path = "../../../awkernel_async_lib"
default-features = false

[dependencies.awkernel_lib]
path = "../../../awkernel_lib"
default-features = false
